#%RAML 1.0 DataType

type: object
properties:
  Location: string
  Time: string
  Wind: string
  Visibility: string
  SkyConditions: string
  Temperature: string
  DewPoint: string
  RelativeHumidity: string
  Status: string